/**
 * This file was generated by the Jeddict
 */ 

package com.gsafer.smartoperation.entity;

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


@Entity
@Table(name="T_PROCESSOR_CONFIG")
public class ProcessorConfig { 

    @Column(name="PROCESSOR_CONFIG_ID",table="T_PROCESSOR_CONFIG",nullable=false)
    @Id
    @GeneratedValue(generator="s_t_processor_config",strategy=GenerationType.SEQUENCE)
    @SequenceGenerator(name="s_t_processor_config",sequenceName="s_t_processor_config")
    private Integer processorConfigId;

    @Column(name="IP",table="T_PROCESSOR_CONFIG",length=16)
    @Basic
    private String ip;

    @Column(name="ETH",table="T_PROCESSOR_CONFIG")
    @Basic
    private short eth;

    @Column(name="STATUS",table="T_PROCESSOR_CONFIG")
    @Basic
    private short status;

    @Column(name="GATEWAY",table="T_PROCESSOR_CONFIG",length=16)
    @Basic
    private String gateway;

    @Column(name="NETMASK",table="T_PROCESSOR_CONFIG",length=16)
    @Basic
    private String netMask;

    @Column(name="CREATE_TIME",table="T_PROCESSOR_CONFIG")
    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date createTime = new java.util.Date();;

    @Column(name="REMARK",table="T_PROCESSOR_CONFIG",length=50)
    @Basic
    private String remark;

    @ManyToOne(targetEntity = HospitalOperation.class)
    @JoinColumn(name="HOSPITAL_OPERATION_ID",referencedColumnName="HOSPITAL_OPERATION_ID",nullable=false,updatable=false)
    private HospitalOperation hospitalOperation;

    public Integer getProcessorConfigId() {
        return this.processorConfigId;
    }

    public void setProcessorConfigId(Integer processorConfigId) {
        this.processorConfigId = processorConfigId;
    }


    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }


    public short getEth() {
        return this.eth;
    }

    public void setEth(short eth) {
        this.eth = eth;
    }


    public short getStatus() {
        return this.status;
    }

    public void setStatus(short status) {
        this.status = status;
    }


    public String getGateway() {
        return this.gateway;
    }

    public void setGateway(String gateway) {
        this.gateway = gateway;
    }


    public String getNetMask() {
        return this.netMask;
    }

    public void setNetMask(String netMask) {
        this.netMask = netMask;
    }


    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }


    public HospitalOperation getHospitalOperation() {
        return this.hospitalOperation;
    }

    public void setHospitalOperation(HospitalOperation hospitalOperation) {
        this.hospitalOperation = hospitalOperation;
    }


    @Override
    public boolean equals(Object obj) {
        if (obj == null) {return false;}
        if (!java.util.Objects.equals(getClass(), obj.getClass())) {return false;}
        final ProcessorConfig other = (ProcessorConfig) obj;
        if (!java.util.Objects.equals(this.getProcessorConfigId(), other.getProcessorConfigId())) {        return false;        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + (this.getProcessorConfigId() != null ? this.getProcessorConfigId().hashCode() : 0);
        return hash;
    }

    @Override
    public String toString() {
        return "ProcessorConfig{" + " processorConfigId=" + processorConfigId + ", ip=" + ip + ", eth=" + eth + ", status=" + status + ", gateway=" + gateway + ", netMask=" + netMask + ", createTime=" + createTime + ", remark=" + remark + '}';
    }

}
